#!/bin/bash
[ -f "/etc/romix/romix.conf" ] || exit 0
. /etc/romix/romix.conf

case $1 in
    true)
        echo "Enable screen power saving"
        echo $BATT_BRIGHTNESS > /sys/class/backlight/acpi_video0/device/backlight/acpi_video0/brightness
    ;;
    false)
        echo "Disable screen power saving"
        echo $AC_BRIGHTNESS > /sys/class/backlight/acpi_video0/device/backlight/acpi_video0/brightness
    ;;
esac
