#!/bin/bash
[ -f "/etc/romix/romix.conf" ] || exit 0
[ -x "/usr/bin/xbacklight" ] || exit 0
. /etc/romix/romix.conf

 username=`cat /tmp/romix/x-current-user`
 userhome=/home/$username
 export XAUTHORITY="$userhome/.Xauthority"
 export DISPLAY=":0"

case $1 in
    true)
        echo "Enable screen power saving"
        su $username -c "/usr/bin/xbacklight -set  $BATT_BRIGHTNESS"
    ;;
    false)
        echo "Disable screen power saving"
        su $username -c "/usr/bin/xbacklight -set  $AC_BRIGHTNESS"
    ;;
esac
 

