#!/bin/sh

set -e

lb config noauto \
	--architectures amd64 \
	--archive-areas "main contrib non-free"	\
	--apt-recommends false \
 	--apt apt \
	--apt-indices false \
	--apt-secure true \
	--apt-source-archives false \
	--distribution stretch \
	--firmware-chroot true \
	--iso-application "ROMIX" \
	--iso-preparer ""\
	--iso-publisher ""\
	--debian-installer live \
	--linux-flavours amd64 \
	--memtest none \
	--security true \
	--updates true \
#	--apt-http-proxy http://localhost:3128/ \
	--linux-packages "linux-image linux-headers" \
	--bootappend-live "boot=live splash components=hostname,user-setup,live-debconfig_passwd,sudo,locales,tzdata,util-linux,xserver-xorg persistence persistence-encryption=luks persistence-media=removable persistence-label=urulu" \
	"${@}"
