#!/bin/sh

set -e

lb config noauto \
	--architectures amd64 \
	--linux-flavours amd64 \
	--apt-recommends false \
 	--apt apt \
	--apt-indices false \
	--memtest none \
	--apt-source-archives false \
	--archive-areas "main contrib non-free"	\
	--firmware-chroot true \
	--debian-installer false \
	--iso-application "ROMIX" \
	--iso-preparer ""\
	--iso-publisher ""\
	--debian-installer live \
	--security true \
	--bootappend-live "boot=live splash persistence persistence-encryption=luks persistence-media=removable persistence-label=urulu" \
	"${@}"

